version: '3.7'

services:
  #
  # SQL data base
  #
  postgres:
    image: postgres:14
    restart: always
    shm_size: 1gb
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - '../sql/backend.sql:/docker-entrypoint-initdb.d/backend.sql'
    environment:
      POSTGRES_USER: 'mempoolstats'
      POSTGRES_PASSWORD: 'mempoolstats'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U mempoolstats']
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "password_encryption=md5"

  #
  # Hasura
  #
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
      - '8082:8080'
    # volumes:
    #   - '../hasura/metadata:/hasura-metadata'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://mempoolstats:mempoolstats@postgres:5432/mempoolstats'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_CORS_DOMAIN: 'http://localhost:3000'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_ADMIN_SECRET: 'my_admin_secret_key'
  
  #
  # Tx crawler
  #
  crawler:
    image: crawler:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - 'postgres'
    restart: always
    environment:
      NODE_ENV: 'production'
      NODE_PG_FORCE_NATIVE: 'true'
      ETHEREUM_WS: 'wss://mainnet.infura.io/ws/v3/b45e47191e764a8b9bdb465f2fe03178' 

#
# Persistent volumes
#
volumes:
  db-data: {}
